/*
	Created by SEADATA\michael.dspain using dbatools Export-DbaScript for objects on dre-jumpbox at 01/15/2026 18:49:13
	See https://dbatools.io/Export-DbaScript for more information
*/
CREATE DATABASE [DBStats]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBStats_Data', FILENAME = N'D:\Data\DBStats_Data.mdf' , SIZE = 22020096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'DBStats_Log', FILENAME = N'L:\Log\DBStats_Log.ldf' , SIZE = 1048576KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

ALTER DATABASE [DBStats] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBStats].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBStats] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBStats] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBStats] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBStats] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBStats] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBStats] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBStats] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBStats] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBStats] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBStats] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBStats] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBStats] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBStats] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBStats] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBStats] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBStats] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [DBStats] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBStats] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBStats] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBStats] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBStats] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBStats] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBStats] SET RECOVERY FULL 
GO

ALTER DATABASE [DBStats] SET  MULTI_USER 
GO

ALTER DATABASE [DBStats] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBStats] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBStats] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBStats] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBStats] SET DELAYED_DURABILITY = FORCED 
GO

ALTER DATABASE [DBStats] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBStats] SET QUERY_STORE = ON
GO

ALTER DATABASE [DBStats] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DBStats] SET  READ_WRITE 
GO

